### ISSUE TITLE
Can't load weights

### ISSUE THREAD

**Issue by colorfuldarkgray** [pshah123/darkflow#1]
**Tried:**
flow --model cfg/tiny-yolo.cfg --load bin/tiny-yolo.weights
**Got:**
Parsing ./cfg/tiny-yolo.cfg
Parsing cfg/tiny-yolo.cfg
Loading bin/tiny-yolo.weights ...
Traceback (most recent call last):
  File "/home/ruy/.virtualenvs/cv/bin/flow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ruy/darkflow/flow", line 4, in <module>
    cliHandler(sys.argv)
  File "/home/ruy/darkflow/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/ruy/darkflow/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/home/ruy/darkflow/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/ruy/darkflow/darkflow/dark/darknet.py", line 83, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 64701556 bytes, found 108399816

**Also tried:**
flow --model cfg/yolov1.cfg --load bin/yolov1.weights
**And got:**
Parsing ./cfg/yolov1.cfg
Parsing cfg/yolov1.cfg
Loading bin/yolov1.weights ...
Traceback (most recent call last):
  File "/home/ruy/.virtualenvs/cv/bin/flow", line 7, in <module>
    exec(compile(f.read(), __file__, 'exec'))
  File "/home/ruy/darkflow/flow", line 4, in <module>
    cliHandler(sys.argv)
  File "/home/ruy/darkflow/darkflow/cli.py", line 26, in cliHandler
    tfnet = TFNet(FLAGS)
  File "/home/ruy/darkflow/darkflow/net/build.py", line 58, in __init__
    darknet = Darknet(FLAGS)
  File "/home/ruy/darkflow/darkflow/dark/darknet.py", line 27, in __init__
    self.load_weights()
  File "/home/ruy/darkflow/darkflow/dark/darknet.py", line 83, in load_weights
    wgts_loader = loader.create_loader(*args)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 105, in create_loader
    return load_type(path, cfg)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 19, in __init__
    self.load(*args)
  File "/home/ruy/darkflow/darkflow/utils/loader.py", line 77, in load
    walker.offset, walker.size)
AssertionError: expect 203934260 bytes, found 789312988

**What is this expected size? I downloaded weight files from pjreddie web**

**Thank you for sharing**

**Comment by colorfuldarkgray** [comment]
Also tried yolo-tiny.weights from your drive with tiny-yolo.cfg (renamed as yolo-tiny.weights) and got the same size error type: AssertionError: expect 64701556 bytes, found 180357512
